
function done(){

  var A=0;
  var B=0;
  var C=0;
  var D=0;
  var E=0;
  var F=0;
  var G=0;
  var H=0;
  var I=0;
  var J=0;
  var K=0;
  var L=0;
  var M=0;
  var N=0;
  
  var ele = document.getElementsByTagName('input');
    

       


        document.getElementById("disp").innerHTML = "";
        var ele = document.getElementsByTagName('input');
        var d=[];
        for(i = 0; i < ele.length; i++) {
            if(ele[i].type="radio") {
              
                if(ele[i].checked)
                {

                  if(ele[i].value!=null)d+= ele[i].value ;
                  
                }
                    

            }
        


          }


  var p=Array.from(d);
 
  

  A+=(parseInt(p[52])+parseInt(p[53])+parseInt(p[55])+parseInt(p[56])+parseInt(p[77])+parseInt(p[79])+parseInt(p[83]));
  B+=(parseInt(p[54])+parseInt(p[57])+parseInt(p[58])+parseInt(p[59])+parseInt(p[92])+parseInt(p[93])+parseInt(p[94]));
  C+=(parseInt(p[11])+parseInt(p[15])+parseInt(p[52])+parseInt(p[54])+parseInt(p[62])+parseInt(p[87])+parseInt(p[95])+parseInt(p[96]));
  D+=(parseInt(p[18])+parseInt(p[80])+parseInt(p[101])+parseInt(p[102])+parseInt(p[103])+parseInt(p[104]));
  E+=(parseInt(p[7])+parseInt(p[8])+parseInt(p[44])+parseInt(p[50])+parseInt(p[84])+parseInt(p[88])+parseInt(p[99])+parseInt(p[100])+parseInt(p[106]));
  F+=(parseInt(p[14])+parseInt(p[45])+parseInt(p[46])+parseInt(p[47])+parseInt(p[48])+parseInt(p[49])+parseInt(p[85])+parseInt(p[86]));
  G+=(parseInt(p[9])+parseInt(p[12])+parseInt(p[13])+parseInt(p[16])+parseInt(p[17])+parseInt(p[19])+parseInt(p[23])+parseInt(p[51])+parseInt(p[78]));
  H+=(parseInt(p[60])+parseInt(p[61])+parseInt(p[63])+parseInt(p[64])+parseInt(p[65])+parseInt(p[90])+parseInt(p[91]));
  I+=(parseInt(p[21])+parseInt(p[37])+parseInt(p[38])+parseInt(p[39])+parseInt(p[40])+parseInt(p[41])+parseInt(p[42])+parseInt(p[43]));  
  J+=(parseInt(p[0])+parseInt(p[1])+parseInt(p[2])+parseInt(p[3])+parseInt(p[20])+parseInt(p[22])+parseInt(p[71])+parseInt(p[98]));  
  K+=(parseInt(p[4])+parseInt(p[29])+parseInt(p[31])+parseInt(p[66])+parseInt(p[67])+parseInt(p[68])+parseInt(p[69]));  
  L+=(parseInt(p[10])+parseInt(p[30])+parseInt(p[72])+parseInt(p[73])+parseInt(p[74])+parseInt(p[75])+parseInt(p[76])+parseInt(p[81]));  
  M+=(parseInt(p[5])+parseInt(p[6])+parseInt(p[28])+parseInt(p[32])+parseInt(p[33])+parseInt(p[34])+parseInt(p[35])+parseInt(p[36]));  
  N+=(parseInt(p[24])+parseInt(p[25])+parseInt(p[26])+parseInt(p[27])+parseInt(p[70])+parseInt(p[89])+parseInt(p[97]));  

// if(A==0 &&B==0 &&C==0 &&D==0 &&E==0  &&F==0 &&G==0 && H==0 &&I==0 &&J==0 &&K==0 &&L==0  &&M==0 &&N==0||(  isNaN(A) || isNaN(B)|| isNaN(C)|| isNaN(D)|| isNaN(E)|| isNaN(F)|| isNaN(G)|| isNaN(H)|| isNaN(I)|| isNaN(J)|| isNaN(K)|| isNaN(L)|| isNaN(M)|| isNaN(N)) )
// {
//   alert ("Wszystkie pola muszą być uzupełnione!");
// }
// else
// {
//   document.getElementById("disp").innerHTML
//   +=  " Osiągnięcia: "
//   + achivement + "<br>"
  
//     + " Władza: "
//   + control + "<br>"
  
//    + " Przynależnośc: "
//   + membership + "<br>";
// }

var wynikiTablica = [A, B, C, D, E, F, G, H, I, J, K, L, M, N];
const wartoscMax = Math.max(...wynikiTablica);

const indexes = [];

for (let index = 0; index < wynikiTablica.length; index++) {
  if (wynikiTablica[index] === wartoscMax) {
    indexes.push(index);
  }
}


if((p.length)!=107)
{

    alert("Nie wszytkie odpowiedzi są zaznaczone!")
          
}
else
{

 if(!isNaN(document.getElementById("disp").innerHTML))
   {
        document.getElementById("disp").innerHTML +=
        "Czujny: " + A + "<br>" +
        "Samotniczy: " + B + "<br>" +
        "Nie-zwyczajny: " + C + "<br>" +
        "Awanturniczy: " + D + "<br>" +
        "Zmienny: " + E + "<br>" +
        "Dramatyczny: " + F + "<br>" +
        "Pewny siebie: " + G + "<br>" +
        "Ostrożny: " + H + "<br>" +
        "Oddany: " + I + "<br>" +
        "Sumienny: " + J + "<br>" +
        "Wygodny: " + K + "<br>" +
        "Władczy: " + L + "<br>" +
        "Ofiarny: " + M + "<br>" +
        "Poważny: " + N + "<br>";
    
   }

  if(!isNaN(document.getElementById("opisWyniku").innerHTML)){
    for (let index = 0; index < indexes.length; index++) {
        document.getElementById("opisWyniku").innerHTML += teksty[indexes[index]] + cechy[indexes[index]] + tabele[indexes[index]];
        document.getElementById("opisWyniku").innerHTML += "<br><br><br><br>"
  }
  }

  

}




}


var tekstCzujny = "<br> <h3>TYP CZUJNY</h3> „TROPICIEL” <br> Nic nie umyka uwagi ludzi o Czujnym typie osobowości. Mają oni wyjątkowo świadomość swojego otoczenia. Wiecznie „walczą o życie”. Anteny ich zmysłów stale łowią napływające z zewnątrz sygnały, natychmiast alarmując, gdy wykryją jakąś nieadekwatność, zgrzyt, dysonans czy zagrożenie, zwłaszcza w kontaktach z innymi ludźmi. Osoby Czujne mają pod tym względem nadzwyczajny słuch. Natychmiast wyczuwają podwójne komunikaty, ukryte motywacje, uniki, dwuznaczność i najdrobniejsze nawet zniekształcenia prawdy, które uszłyby uwagi mniej wytrawnych obserwatorów. Tak ukierunkowana osoba Czujna w naturalny sposób przyjmuje, zarówno w życiu prywatnym, jak i publicznym, rolę krytyka obyczajów, strażnika moralności, ombudsmana  i krzyżowca – zawsze gotowa do walki z wypaczeniami, które zatruwają ludzkie sprawy, a zwłaszcza z nadużyciami władzy. <br><br>";
var cechyCzujny = "SZEŚĆ CECH CHARAKTERYSTYCZNYCH: <br> Oto sześć kluczowych cech i postaw charakterystycznych dla typu Czujnego. Osoba z silną tendencją do Czujności będzie wykazywać większą liczbę tych zachowań i z większą intensywnością niż ktoś, w kogo osobowości typ ten jest mniej dominujący. <br>  1.	Autonomia. Ludzie Czujni są wybitnie niezależni. Liczą się tylko z własną opinią, nie oczekują od nikogo wsparcia ani rady, łatwo podejmują decyzje i potrafią się o siebie zatroszczyć. <br> 2.	Ostrożność. W stosunkach z ludźmi zachowują się ostrożnie. Dobrze prześwietlą kandydata na partnera przed zawarciem związku. <br> 3.	Spostrzegawczość. Są dobrymi słuchaczami, z uchem wyczulonym na subtelności tonu i różne poziomy komunikatów. <br> 4.	Samoobrona. Nie są strachliwi, nie zawahają się stawić czoła przeciwnościom, zwłaszcza gdy zostaną zaatakowani. <br> 5.	Wrażliwość na krytykę. Przyjmują krytykę bardzo serio, nie doznając przy tym uczucia zagrożenia. <br> 6.	Wierność. Bardzo wysoko cenią sobie wierność i lojalność. Nigdy nie uważają, by im się po prostu należały, i wiele uczynią, by na nie zasłużyć.<br><br> ";
var tabelaCzujnyPart1 = "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Lojalny, przytomny, łatwo kwestionuje autorytety, demaskator, sceptyk, strażnik norm, adwokat diabła, ma ograniczone zaufanie, ostrożny, odważny w walce, w stresie bardzo podejrzliwy.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Bądź precyzyjny i uczciwy, nie lawiruj, nie pozostawiaj niedomówień.<br>- Uczciwie ujawniaj mocne strony i zagrożenia<br>- Ne daj się opanować „czarnej wizji” - badaj kolejne kroki.<br>- Licz się z lękiem i podejrzliwością w sytuacjach niejasnych i niepewnych.<br>- Buduj realistyczne partnerstwo, dyskontuj tendencje do nadmiernej uległości lub buntu.<br></td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Potrzebuje wyraźnego podziału władzy i jasno definiowanych problemów.<br>- Doceń rolę lojalnego, rzetelnego, autorytatywnego, życzliwego pracownika.<br>- Rób to, co deklarujesz - zasłużysz na lojalność.<br>- Daj mu czas na analizowanie danych i sytuacji.<br>- Zachowuj spokój i życzliwość, gdy zadaje wiele trudnych pytań.<br>- Zabezpiecz możliwość mówienia, co myśli o innych.<br>- Doceń lojalność i zaangażowanie pomimo wątpliwości, jako ostateczność wskaż wspólnego wroga, zewnętrzne zagrożenie.<br></td></tr><tr><th>MOTYWOWANIE</th><td>- Dostosuj wynagrodzenia i inne bodźce do jej/jego poczucia sprawiedliwości.<br>- Wspieraj na początku i tuż przed ukończeniem zadania (najwięcej niepokoju).<br>- Zapraszaj do planowania, sprawozdawczości, kontroli, raportów.<br>- Licz się z tym, że potrzebuje więcej czasu na pracę własną niż inni.<br>- Przypominaj dyskretnie o rozrywkach i relaksie.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Szanuj autonomię partnera – unikaj sytuacji i komunikatów, które dają do zrozumienia, że partner zależy od ciebie. Bądź jasny i czytelny w swoich zamiarach – nie sprawiaj wrażenia, że coś ukrywasz. Jeśli istnieje konieczność wyrażenia krytyki – zrób to otwarcie i zdecydowanie. Dawaj do zrozumienia, że jesteś lojalny wobec swojego partnera – jeśli wyczuje od ciebie jakikolwiek sygnał, że coś ukrywasz, masz coś „na boku” może zerwać rozmowę. Dotrzymuj obietnic i zobowiązań. Dbaj o zachowanie (z twojej strony) jasnych i klarownych zasad dotyczących prowadzonych rozmów. Zachęcaj partnera do podejmowania kolejnych kroków w rozmowach. Nie pomijaj niepokoju wyrażanego przez partnera. O swoich zamierzeniach informuj z dużym wyprzedzeniem. Daj czas partnerowi na przemyślenia i przyzwyczajenie się do zmiany, bądź ";
var tabelaCzujnyPart2 = "przygotowany na początkowy opór. Pamiętaj – tego typu osoby bacznie obserwują i notują co mówisz, a co robisz. </td></tr></table>";
var tabelaCzujny = tabelaCzujnyPart1 + tabelaCzujnyPart2;


var tekstSamotniczy = "<br> <h3>TYP SAMOTNICZY</h3>„PUSTELNIK”<br> Samotnicy nie potrzebują nikogo oprócz samych siebie. Nie porusza ich podekscytowany tłum, wolni są od chęci przypodobania się i wywierania wrażenia. Nie widać u nich zaangażowania i emocji, które zżerają tylu innych ludzi. Ten niedostatek uczuć i intymności wynagradza im jasność widzenia. Jako antropolodzy, przyrodnicy, matematycy, fizycy, filmowcy, pisarze czy poeci zdolni są odkryć i zarejestrować te strony naszej egzystencji, na które tak często czynią nas ślepymi namiętności.<br><br>"
var cechySamotniczy = "SZEŚĆ CECH CHARAKTERYSTYCZNYCH: <br> Oto sześć cech kluczowych dla rozpoznania typu Samotniczego. Osoba z silną tendencją Samotniczą będzie wykazywać większą liczbę tych zachowań i z większą intensywnością niż ktoś, w kogo osobowości typ ten jest mniej dominujący.<br>1.	Na uboczu. Ludzie z samotniczym typem osobowości mają niewielkie potrzeby towarzyskie i najlepiej czują się w samotności.<br>2.	Niezależność. Są samowystarczalni i nie potrzebują związków z innymi, by cieszyć się swymi przeżyciami i dawać sobie radę w życiu.<br>3.	Zimna krew. Są zrównoważeni, spokojni, beznamiętni, niewzruszeni, wolni od sentymentów.<br>4.	Stoicyzm. Wydają się równie obojętni na ból i na przyjemność.<br>5.	Powściągliwość seksualna. Nie rządzą nimi namiętności erotyczne. Choć umieją cieszyć się seksem, nie cierpią z powodu jego braku.<br>6.	Realizm. Nie działają na nich ani pochwały, ani krytyka. Potrafią samodzielnie oceniać swe postępowanie.<br><br>"
var tabelaSamotniczy = "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Obserwator, analityk, myśliciel, filozof, pustelnik, powściągliwy, aemocjonalny, zdystansowany, trzeźwy, beznamiętny, spokojny w kryzysie (czasem w silnym stresie – dramatyczny).</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>Utrzymuj dystans do kontaktu wystarczy fax, poczta elektroniczna, telefon im bardziej będziesz starać się skłonić go do kontaktu, tym większy będzie opór.<br>- Nie naruszaj jej (jego) granic.<br>- Zapowiadaj wizyty.<br>- Rozmawiaj o intelektualnych  zainteresowaniach, powstrzymaj emocje.<br>- Kontroluj swoje projekcje (co mu przypisujesz).<br>- Licz się z wycofaniem po kontakcie. Strukturalizuj sytuacje konfliktowe.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Ograniczaj występy i spotkania publiczne. Pozwól na pracę w domu, wycofanie pomiędzy spotkaniami.<br>- Dziel pracę na odcinki, proś o cząstkowe sprawozdania pisemne.<br>- Jasno określ ramy tezy początkowe zadania (mogą grzęznąć w szukaniu detali). Czas, cel, kryteria.<br>- Wykorzystuj, że S. nie przejmuje się wewnętrznymi układami w firmie - robi swoje.</td></tr><tr><th>MOTYWOWANIE</th><td>- Kluczem do wydajności są warunki pracy (a nie „bodźce”) i możliwość izolacji, super oprogramowanie, dostęp do danych.<br>- Motywatory wypływające „z systemu”.<br>- Nie obsadzaj go w roli człowieka, który ma zmotywować innych (nie rozumie emocji innych i źle zarządza problemami personalnymi).</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Bądź przygotowany na negocjacje typu „azjatyckiego” – bierne i ciche – nigdy nie wiesz do końca, na czym stoisz. Kontroluj emocje . Twój partner może wydawać się przez dużą część czasu niezainteresowany tematem negocjacji – tym, co mówisz, pomysłami, problemami. Nie zrażaj się tym. Testuj zrozumienie, zadawaj pytania, nie przesadzaj z kontaktem wzrokowym. Zachowaj dystans. Pamiętaj: twój partner będzie cię obserwował i prowokował, abyś ty pierwszy się odsłonił, wyszedł z propozycją. Nie angażuj jego uwagi na siłę. Daj mu pozostać biernym jeśli tego potrzebuje. Bądź cierpliwy i powoli przechodź od punktu do punktu (systematycznie) zgodnie z planem rozmowy. Nie irytuj się i nie trać kontroli nad sobą i sytuacją. Zanim przejdziesz do spraw większego kalibru zaczynaj od tych mniejszych. Bądź zawsze przygotowany do spotkania.</td></tr></table>";

var tekstNiezwyczajny = "<br><h3>TYP NIE – ZWYCZAJNY</h3>„ORYGINAŁ”<br>Ludzie Nie – zwyczajni są inni niż większość. To marzyciele, wizjonerzy, mistycy, poszukiwacze przeżyć duchowych. Kroczą w rytmie odmiennym od konwencjonalnych zwyczajów większości. Są prawdziwymi oryginałami i wyrastają ponad przeciętność: czasem jako ekscentrycy, czasem jako geniusze.<br><br>"
var cechyNiezwyczajny = "SZEŚĆ CECH CHARAKTERYSTYCZNYCH: <br>Oto sześć cech kluczowych dla rozpoznania typu Nie – zwyczajnego. Osoba z silną tendencją tego rodzaju będzie wykazywać większą liczbę tych zachowań i z większą intensywnością niż ktoś, w kogo osobowości typ ten jest mniej dominujący.<br>1.	Życie wewnętrzne. Ludzie Nie – zwyczajni trzymają się własnych odczuć i przekonań, bez względu na to, czy inni rozumieją i akceptują ich specyficzny światopogląd i podejście do życia.<br>2.	Własny świat. Są niezależni i zamknięci w sobie, nie odczuwają silnej potrzeby bliskich związków.<br>3.	Wszystko po swojemu. Są niewrażliwi na konwenanse, sami stwarzają sobie oryginalny, niezwykły, często ekscentryczny styl życia.<br>4.	Wyższa rzeczywistość. Są otwarci na wszystko, interesują się okultyzmem i zjawiskami paranormalnymi.<br>5.	Skłonności metafizyczne. Pociąga ich myśl abstrakcyjna i spekulatywna.<br>6.	Oczy zawsze otwarte. Choć są skupieni na sobie i podążają za głosem swojego serca i rozumu, potrafią obserwować innych ludzi i są szczególnie wrażliwi na to, jak inni na nich reagują.<br><br>"
var tabelaNiezwyczajny = "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Ekscentryk oryginał, może sprawiać wrażenie dziwaka, inny niż większość, angielski ekscentryk albo polityk w swetrze, żyje we własnym świecie, po swojemu, ma skłonności metafizyczne lub do „filozofowania”, wrażliwy na reakcje ludzi na siebie, w stresie dzieli na „my” i „oni”.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Stwórz mu niszę, mikrośrodowisko tolerujące jego ekscentryczność.<br>- Okaż zainteresowanie jego światem (nie musisz go wyznawać).<br>- Używaj w sprawach zasadniczych metafor i porównań z „jego” świata.<br>– Łagodnie, ale stanowczo powracaj do spraw „przyziemnych”, nie daj się zatopić w dygresjach.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Nie nastawiaj się na dożywotni kontrakt.<br>- Zarządzaj przez cele i uwzględniaj, że irytuje niektórych ludzi (zwłaszcza DO-erów).<br>- Nie oczekuj zbyt wiele, jeśli pracuje tylko dla pieniędzy, a jego energia jest gdzie indziej  i zawieraj jasne kontrakty na to, co na kiedy zrobi, jaki będzie produkt.<br>- Sprawdzaj, czy załatwił „przyziemne” sprawy, których się podjął.</td></tr><tr><th>MOTYWOWANIE</th><td>- Doceniaj za niepowtarzalność, a nie „pomimo” niej.<br>- Dopiero z tej perspektywy stawiaj „przyziemne” wymagania.<br>- Odnoś zadania do „jego” świata – szukaj pomostu celów firmy i jego wartości.<br>- Jeśli jest wybitny - wyręczaj w załatwianiu dupereli.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Bądź przygotowany na niekonwencjonalne pomysły i rozwiązania ze strony partnera.  Staraj się rozumieć jego stanowisko, pomysły, propozycje, choć nie musisz się wew. z nim zgadzać – mogą one wydawać się bardzo obce i odległe z twojego punktu widzenia. Unikaj sztywnego trzymania się konwenansów i zasad – bądź elastyczny. Trzymaj jednak strukturę spotkania – plan, cel, ramy czasowe.</td></tr></table>";

var tekstAwanturniczy = "<br><h3>TYP AWANTURNICZY</h3>„POSZUKIWACZ PRZYGÓD”<br>Do odważnych świat należy – oto hasło Awanturnika. Któż jeśli nie Poszukiwacze Przygód dokonuje wielkich kroków ludzkości – przepływa oceany, przełamuje barierę dźwięku, ląduje na księżycu? Ludzie z tym typem osobowości mają odwagę podjąć wyzwania, przed którymi drży większość śmiertelników. Nie ograniczają ich takie jak nas lęki i troski. Żyją na ostrzu noża, podważają wszelkie bariery i ograniczenia, ryzykują wszystko w fascynującej rozgrywce ze śmiercią. Bez ryzyka nie ma wygranej, powiadają. Tak naprawdę, to dla Awanturnika wygraną jest samo ryzyko.<br><br>"
var cechyAwanturniczy = "OSIEM CECH CHARAKTERYSTYCZNYCH<br>Oto osiem cech kluczowych dla rozpoznania typu Awanturniczego. Osoba z silną tendencją Awanturniczą będzie wykazywać większą liczbę tych zachowań i z większą intensywnością niż ktoś, w kogo osobowości typ ten jest mniej dominujący.<br>1.	Nonkonformizm. Poszukiwacze Przygód żyją w zgodzie ze swoim wewnętrznym kodeksem wartości. Inni ludzie i normy społeczne nie mają na nich większego wpływu.<br>2.	Podejmowanie rękawicy. Do odważnych świat należy. Awanturnicy uwielbiają smak ryzyka i bez namysłu angażują się w niebezpieczne przedsięwzięcia.<br>3.	Niezależność. Nie martwią się za bardzo o innych, uważają bowiem, że każda istota ludzka powinna sama odpowiadać za siebie.<br>4.	Dar przekonywania. Awanturnicy to krasomówcy, mistrzowie w subtelnej sztuce zdobywania przyjaciół i wywierania wpływu.<br>5.	Niespokojny duch. Kochają ruch. Nie usiedzą na miejscu, coś ich pędzi w świat, do nowych odkryć, wciąż dalej i dalej. Nie dbają o posadę, radzą sobie dzięki swym talentom, pomysłowości i bystrości.<br>6.	Mały dzikus. W dzieciństwie i w okresie dojrzewania zdradzają skłonność do psot i chuligańskich wyskoków.<br>7.	Człowiek z żelaza. Są odważni, twardzi i wytrzymali fizycznie. Stawią czoło każdemu, kto ośmieli się z nimi zadrzeć.<br>8.	Niczego nie żałować. Awanturnicy żyją w teraźniejszości. Nie doznają poczucia winy z powodu tego, co było, ani lęku przed przyszłością. Życia doświadcza się tu i teraz.<br><br>"
var tabelaAwanturniczy = "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Kaskader, ryzykant, gracz w pokera życiowego, poszukiwacz zmian, przygody, nowych wrażeń, może być impulsywny, agresywny i niezależny, krasomówczy - dar przekonywania, żyje teraz i tutaj, niezbyt troszczy się o innych.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Dotrzymać kroku (ale zachować swoją miarę).<br>- Minimalizuj wzajemne powiązania - pilnuj umów.<br>- Daj mu przestrzeń, pozwól odchodzić i powracaćnie próbuj go zmieniać.<br>- Baw się dobrze.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Jeśli ma pomysły i inicjatywę wspieraj go dbając o kontynuację, gdy mu się znudzi.<br>- Ustawiaj go solo, a nie na średnich szczeblach w statycznej strukturze.<br>- „Osłaniaj” innych przed odruchami jego agresji- wykorzystaj zmysł handlowy, wodzirejski, komiwojażerski.<br>- Uważaj na potrzebę łamania norm.</td></tr><tr><th>MOTYWOWANIE</th><td>- Nie może się nudzić; zmienne, żywe, aktywne zadania krótkoterminowe.<br>- „Hazardowe” premie.<br>- Nie strasz, nie przypominaj o zagrożeniach chyba, że chcesz go jeszcze bardziej podniecić.<br>- Pozwól na własny rytm pracy.<br>- Po fazie planów i uruchomienia - dbaj o realia.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Stwarzaj atmosferę wyzwania (w trakcie negocjacji). Bądź stanowczy ale elastyczny, kiedy zajdzie taka potrzeba. Bądź przygotowany na zmiany – zwroty w prezentowaniu stanowiska. Staraj się utrzymywać pewien rodzaj napięcia emocjonalnego. Dawaj sygnały twemu partnerowi, że ma swobodę wyboru – nie zapędzaj go w „kozi róg”, niech zachowa swoją niezależność. Przyjmuj argumenty – potwierdzaj , że rozumiesz. Wyrażaj się pozytywnie na temat jego propozycji, ale nie rezygnuj ze swojego stanowiska. Dbaj o dokumentację rozmów (poczynionych ustaleń).</td></tr></table>";

var tekstZmienny = "<br><h3>TYP ZMIENNY EMOCJONALNIE</h3>„OGIEŃ I LÓD”<br>Dla ludzi z osobowością typu zmiennego życie to szalona jazda kolejką górską z wesołego miasteczka, do której koniecznie chcieliby zabrać wszystkich. Każdy ich oddech jest przesycony intensywnością uczuć, na szczycie czy w dolinie. Ludzie Zmienni łakną przeżyć, rzucają się więc w nową miłość lub nowy styl życia na oślep, bez oglądania się wstecz. Żaden inny typ, nawet Dramatyczny, nie jest tak wrażliwy w swoim pragnieniu, by stanowić jedno z życiem i ludźmi. I żaden też nie potrafi tak dobrze znosić zmiennej pogody uczuciowej, którą niesie ten gorączkowy sposób życia.<br><br>"
var cechyZmienny = "SIEDEM CECH CHARAKTERYSTYCZNYCH:<br>Oto siedem cech kluczowych dla rozpoznania typu Zmiennego. Osoba z silną tendencją tego rodzaju będzie wykazywać większą liczbę tych zachowań i z większą intensywnością niż ktoś, w kogo osobowości typ ten jest mniej dominujący.<br>1.	Romantyczne przywiązanie. Ludzie Zmienni muszą zawsze być głęboko zaangażowani w romantyczny związek.<br>2.	Intensywność. W każdym związku są namiętni i skoncentrowani. Między nimi i innymi ludźmi nie ma spraw błahych, niczego nie traktują lekko. <br>3.	Serce na wierzchu. Okazują swoje emocje. Są wrażliwi i uczuciowi. Wkładają serce we wszystko co robią.<br>4.	Bez cugli. Są niepohamowani, spontaniczni, kochają dobrą zabawę i nie boją się ryzyka.<br>5.	Aktywność. Energia to cecha charakterystyczna typu Zmiennego. Tacy ludzie są żywotni, twórczy, wiecznie zajęci, pełni inicjatywy i potrafią pociągnąć za sobą innych.<br>6.	Otwarty umysł. Są ciekawi świata i mają bogatą wyobraźnię. Lubią próbować nowej roli, wchodzić w odmienne kultury i system wartości, podążać nowymi ścieżkami.<br>7.	Inna świadomość. Mają dar dystansowania się od rzeczywistości, kiedy staje się zbyt twarda i bolesna.<br><br>"
var tabelaZmienny = "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Żywe srebro, ogień i lód, niespokojny duch, kapryśny, idealizuje, zapala się, rozczarowuje, dewaluuje. Romantyk, impulsywny, serce na dłoni, ciekawy świata, czasem odrzuca lub prowokuje odrzucanie, zwłaszcza w stresie.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Trzymaj się swego centrum oraz struktury relacji (ograniczenia w miejscu i czasie).<br>- Z tej pozycji pozwalaj się wynosić i detronizować utrzymując dystans i pogodę ducha.<br>- Proś o wyjaśnienia jej odczuć, motywacji zachowań (może zakładać że będziesz zgadywać myśli).<br>- Okazuj ciepło, oddanie, życzliwość.<br>- Nie bierz na serio wszystkich dramatycznych gestów.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Bacz na idealizowanie, wynoszenie cię – oswajaj ze swoimi ograniczeniami i wadami.<br>- Licz się z tym, że angażuje się w firmowe plotki, intrygi.<br>- Licz się z tym że może być wymagająca i kapryśna, „trudna”, ale równoważy to twórcze podejście do pracy i okresowo - wielkie zaangażowanie.</td></tr><tr><th>MOTYWOWANIE</th><td>- Uskrzydla ją (jego) poczucie „szczególnej” więzi z szefem (realne na krótki i średni dystans).<br>- W ramach tego co realne traktuj ją (go) jako specjalną osobę do specjalnych zadań.<br>- Pamiętaj, jak ważna jest struktura - zadań, kontraktu, rozliczeń - sprawdzaj, czy wie za co, na jakich warunkach dostaje takie, a nie inne płace i nagrody.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Dbaj o ciepłą i przyjazną atmosferę rozmów. Zadawaj pytania, testuj zrozumienie, proś o wyjaśnienie stanowiska – twój partner może zakładać w myślach, że wiesz, o co mu chodzi. Trzymaj strukturę rozmowy: plan, cel, ramy czasowe i naprowadzaj na istotę problemu. Utrzymuj kontakt wzrokowy. Rób obiektywizowane notatki z poczynionych ustaleń.</td></tr></table>";

var tekstDramatyczny = "<br><h3>TYP DRAMATYCZNY</h3>„PRIMADONNA”<br>Typ dramatyczny to przede wszystkim serce. Ludzie o tym typie osobowości mają wielki dar przeżywania emocji, dzięki któremu ubarwiają życie wszystkim wokół siebie. Jeżeli są obdarzeni jakimś talentem, potrafią przetworzyć ludzkie uczucia w najwyższe formy sztuki. W życiu codziennym ich dowcip, uśmiech, poczucie piękna, fantazja i zmysłowość potrafią tchnąć ducha w całą gromadę skrępowanych, nie znających się ludzi. Dla osoby, którą cechuje ten rozpowszechniony typ osobowości, cały świat jest sceną. Życie nie bywa dla niej nieciekawe i nudne – a już na pewno nie dla jej otoczenia. Wokół osób Dramatycznych unosi się atmosfera ekscytacji; w ich życiu ciągle coś się dzieje.<br><br>"
var cechyDramatyczny = "SIEDEM CECH CHARAKTERYSTYCZNYCH<br>Oto siedem cech kluczowych dla rozpoznania typu Dramatycznego. Osoba z silnym aspektem Dramatycznym będzie przejawiała wymienione niżej zachowania częściej i z większą intensywnością niż osoba, u której typ ten jest słabiej zarysowany.<br>1.	Emocjonalność. Ludzie Dramatyczni żyją w świecie emocji. Przede wszystkim odczuwają. Łatwo uzewnętrzniają emocje i zachowują się w sposób afektowany. Na wydarzenia życiowe reagują emfatycznie i potrafią szybko zmieniać nastroje.<br>2.	Barwność. Są witalni i łakomi życia. Mają bogatą wyobraźnię, opowiadają zajmujące historie, pociągają ich romanse i melodramaty.<br>3.	Potrzeba przyciągania uwagi. Osoby Dramatyczne lubią być dostrzegane. Często bywają ośrodkiem zainteresowania i rozkwitają w sytuacji, gdy wszystkie oczy skierowane są na nie.<br>4.	Dbałość o wygląd. Wiele uwagi poświęcają swojemu wyglądowi, interesują się strojami, stylami i modą. <br>5.	Urok seksualny. Z ich wyglądu i zachowania widać, że cieszą się swoją seksualnością. Są czarującymi uwodzicielami.<br>6.	Łatwość zaangażowania. Ufają innym, potrafią więc bardzo szybko zaangażować się w nowy związek.<br>7.	Entuzjazm. Ludzie o Dramatycznym typie osobowości ochoczo podchwytują nowe idee i są podatni na sugestie.<br><br>"
var tabelaDramatyczny = "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Życie na scenie, czasem ekspresja i środki mocne niewspółmiernie do celu; męska i kobieca prowokacja, erotyczna zazdrość, potrzeba uwagi, intensywność, wrażeń,łatwo się irytuje,  ale i pozytywnie unosi zatraca poczucie czasu (spóźnienia).</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Pamiętaj, że oprócz informacji, procedur zadań potrzebuje kontaktu emocjonalnego.<br>- Przypominaj o skuteczności i rezultatach, powracaj w rozmowie do faktów i wymogów sytuacji.<br>- Reaguj bezpośrednio na emocjonalne wzburzenia ale nie daj się ponieść: szybko miną.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>Przypominaj o czasie zegarowym , planie dnia, ustaleniach, produktach, terminach.<br>- Dopilnuj w wykonywaniu „trywialnych” zdań - dopełnianiu formalności, nietwórczych prac.<br>- Licz się z rozmyciem i zmniejszeniem mobilizacji przed finałem.<br>- Baw się i ograniczaj skutki jego/jej komedianctwa.</td></tr><tr><th>MOTYWOWANIE</th><td>- Gwarantuj „występy”, wyróżniaj przy innych.<br>- Dawaj twórcze zadania.<br>- Doceniaj zmysł estetyczny.<br>- Podtrzymuj kontakt i oddanie „na dobre i na złe”, nie izoluj, nie odrzucaj.<br>- Czasem przypomnij o kontakcie z rzeczywistością.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Podkreślaj pozytywne aspekty twojego stanowiska (twoich interesów). Czasem (jeśli sytuacja pozwala) rzuć komplement na temat wyglądu (ubioru) twojego partnera. Dziel się swoimi emocjami i wczuwaj się (dawaj do zrozumienia, że „odbierasz” jego emocje) w emocje partnera. Utrzymuj kontakt wzrokowy. Słuchaj aktywnie - wtrącaj swoje propozycje i konkretne rozwiązania. Traktuj (i dawaj do zrozumienia) problem negocjacji i partnera jako coś szczególnego, wyjątkowego. Argumenty podkreślaj wyrażaniem emocji (werbalnie i niewerbalnie). Równoważ to na poziomie intelektualnym (merytorycznym). Jeśli trzeba bądź ciepły i dawaj wsparcie. Tonizuj i dyscyplinuj emocje partnera. Hamuj zapał do kreowanych przez partnera nowych pomysłów – namawiaj do spokojnego rozważania argumentów za i przeciw. Sprawdzaj czy wysłuchał cię i zrozumiał.</td></tr></table>";

var tekstPewnySiebie = "<br><h3>TYP PEWNY SIEBIE</h3>„GWIAZDA”<br>Jednostki Pewne Siebie wybijają się z tłumu. To przywódcy, gwiazdy pierwszej wielkości; przykuwają uwagę tak w sferze publicznej, jak prywatnej. Gwiazdorskie cechy rodzą się z wysokiego mniemania o sobie, szacunku dla siebie, pewności siebie – wszystkie te wyrażenia zwrotne wskazują na wiarę i oddanie swoim celom. Ta mistyczna wiara w siebie w połączeniu z właściwą temu typowi ambicją potrafi nawet próżne rojenia zamienić w rzeczywistość.<br><br>"
var cechyPewnySiebie = "DZIEWIĘĆ CECH CHARAKTERYSTYCZNYCH:<br>Oto dziewięć cech i sposobów zachowania kluczowych dla typu Pewnego Siebie. Osoba z silnym aspektem Pewnym Siebie będzie przejawiać więcej tych cech i z większą intensywnością niż osoba z mniejszą domieszką tego typu.<br>1.	Wysokie mniemanie o sobie. Ludzie Pewni Siebie wierzą w siebie i w swoje zdolności. Ani przez chwilę nie wątpią, że są jedyni w swoim rodzaju i że nie znaleźli się na tej planecie przez przypadek.<br>2.	Poczucie ważności. Spodziewają się, że w każdej sytuacji będą traktowani w sposób szczególny.<br>3.	Ambicja. Nie ukrywają swoich ambicji ani możliwości.<br>4.	Talenty polityczne. Dla osiągnięcia swoich celów sprawnie wykorzystują siły i zdolności innych ludzi, dobrze sobie z nimi radzą.<br>5.	Potrzeba współzawodnictwa. Dobrze czują się w atmosferze konkurencji, uwielbiają wspinać się na sam szczyt hierarchii i pozostawać tam. <br>6.	Pozycja społeczna. Identyfikują się z ludźmi na wysokich stanowiskach i o dużym prestiżu.<br>7.	Fantazje o wielkości. Wyobrażają sobie siebie jako bohaterów, gwiazdy, czołowe postacie w swojej dziedzinie.<br>8.	Samoświadomość. Posiadają wnikliwą świadomość własnych myśli, doznań i stanu ducha.<br>9.	Poczucie godności. Z naturalną gracją przyjmują komplementy, pochwały oraz wyrazy podziwu. Mają poczucie, że im się to należy.<br><br>"
var tabelaPewnySiebie= "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Lider, gwiazdor, pani-pan JA, czuły na swoim punkcie, przeświadczony o swojej wyjątkowości., komiwojażer. Cechują go tupet,  gracja, poczucie wyjątkowości, w stresie przewrażliwiony na temat własnej osoby.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- „Szczególne zasady”.<br>- Docenianie i uznawanie bez oczekiwania wzajemności.<br>- Dyskutując, konfrontując się mów o faktach, zdarzeniach, zachowaniach, ale nie jego „Ja”.<br>- Krytykę poprzedzaj uznaniem.<br>- Wysłuchuj, gdy jest wzburzony, nie licz na empatię- informuj jasno o swoich potrzebach.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Dyskretnie ale stanowczo bacz, czy nie przekracza norm, umów i lojalności prowadząc swoją „politykę” prowadzącą do sukcesu i władzy. Nie daj się uwieść.<br>- Wspieraj jego karierę - tam gdzie jest firmie potrzebny pozwól mu być na szczególnych zasadach.<br>- Pomagaj mu poznawać i respektować punkty widzenia i uczucia innych.</td></tr><tr><th>MOTYWOWANIE</th><td>- Okazuj zainteresowanie.<br>- Powierzaj szczególne zadania w specjalnym towarzystwie.<br>- Pozwalaj na indywidualne podejście do zadań i ludzi: nie podcinaj skrzydeł.<br>- Zwolnij z zadań, w których nie jest niezastąpiony.<br>- Pamiętaj, że wbrew pozorom źle znosi krytykę lub źle traktuje krytykujących.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Dawaj do zrozumienia przy każdej okazji, jak ważny jest twój partner. Nie oczekuj, że będzie on ciebie pytał o twoje potrzeby lub będzie wykazywał chęć głębszego zrozumienia twojego stanowiska, czy twoich interesów – komunikuj je sam. Podkreślaj wyjątkowość i szczególność sytuacji negocjacji (wraz z jego udziałem). Obdarzaj komplementami i pochwałami (szczególnie jego realne zasługi w procesie negocjacji) ale nie podkładaj się. Nie oczekuj pochwał ze strony partnera. Trzymaj kurs – kieruj uwagę na istotę problemu. Bardzo ostrożnie wyrażaj krytykę. Trzymaj strukturę rozmowy – plan, cel, ramy czasowe. Uważaj – czasem osoby PS moją skłonność do beztroskiego zawierania umów, z których próbują się potem wycofać.</td></tr></table>";

var tekstOstrozny = "<br><h3>TYP OSTROŻNY</h3>„DOMATOR”<br>Ludzie wrażliwi czują się mocni tylko we własnym, małym świecie, wśród osób dobrze sobie znanych. Dla kogoś z tym rozpowszechnionym typem osobowości swojskość oznacza komfort psychiczny, zadowolenie i inspirację. Domatorzy, choć unikają licznego towarzystwa i nie łakną sławy, mogą zyskać rozgłos dzięki swym twórczym talentom. W bezpiecznym emocjonalnie środowisku, wśród nielicznych, najbliższych przyjaciół i członków rodziny, ich wyobraźnia i duch odkrywczy nie znają granic. W świecie swych myśli, uczuć i fantazji odnajdują wolność.<br><br>"
var cechyOstrozny = "SZEŚĆ CECH CHARAKTERYSTYCZNYCH:<br>Oto sześć kluczowych cech typu Wrażliwego. Osoba z silna tendencją do Wrażliwości będzie wykazywała większa liczbę wymienionych niżej zachowań i z większą intensywnością niż ktoś, w kogo osobowości typ ten jest mniej dominujący.<br>1.	Zamiłowanie do swojskości. Jednostki wrażliwe wolą to, co znane, od tego, co nieznane. Dobrze się czują ze swymi nawykami i rutynowymi czynnościami, a nawet potrafią czerpać z nich natchnienie.<br>2.	Wrażliwość na opinię. Bardzo troszczą się o to, co myślą o nich inni ludzie.<br>3.	Rozwaga. W kontaktach z ludźmi zachowują się rozważnie i dyskretnie. Nie wydają pochopnych sądów i nie angażują się, dopóki nie upewnią się, co jest słuszne.<br>4.	Uprzejma rezerwa. W towarzystwie starają się zachowywać grzecznie, ale powściągliwie.<br>5.	Potrzeba wyraźnych ram. Zarówno w pracy zawodowej jak i w kontaktach towarzyskich funkcjonują najlepiej, występując w dobrze określonej roli: gdy dokładnie wiedzą, czego od nich się oczekuje, co powinni mówić i jak się zachowywać.<br>6.	Zamknięcie w sobie. Ludzie Wrażliwi nie są skorzy do dzielenia się swoimi najgłębszymi myślami i uczuciami, nawet z osobami najbliższymi.<br><br>"
var tabelaOstrozny= "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Wrażliwy, potrzebuje kontaktu, ale bardzo ostrożny, konserwatywny, wycofujący się, często esteta, uprzejmy z rezerwą, „chowa się” za tym, co znane.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Pomóż mu „uwić gniazdko”, a praca stanie się drugim domem.<br>- Jego milczenie nie jest wyrazem wyższości.<br>- Ucz się akceptować go jaki jest („wrażliwiec to skarb”), nie aktywizuj go na siłę.<br>- Pozwól oswoić się ze sobą, zanim przystąpicie do aktywnej współpracy.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Stwórz mały zespół, w którym powstanie duża zażyłość.<br>- Oszczędzaj kontaktów z obcymi.<br>- Bardzo dokładnie określ ramy, procedury, rolę.<br>- Nawet nie zmuszaj do telefonowania do obcych.<br>- Pomóż mu ochraniać się profesjonalną maską, rolą - nie demaskuj jej.</td></tr><tr><th>MOTYWOWANIE</th><td>- Zapewnij bezpieczeństwo.<br>- Dawaj zadania, w których się przełamie ale z niewielkim kosztem    i dużym sukcesem.<br>- Funduj aprobatę z zewnątrz.<br>- Nie wystawiaj jej (jego) do negocjacji, handlu, PR.<br>- Doceniaj zmysł estetyczny, atmosferę domową, którą tworzy.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Stwórz przyjemną i ciepłą atmosferę rozmów. Nie naciskaj na partnera aby koniecznie „coś powiedział” (zabrał głos) – daj mu czas na oswojenie się z sytuacją i tobą. Jeśli nawet rozpoznasz jakiej maski używa w kontakcie z tobą twój partner – zachowaj tę wiedzę dla siebie. Dawaj dużo (ale powściągliwych) sygnałów pozytywnych dotyczących jego osoby: jego udziału w rozmowach. Podkreślaj jego pozytywny wkład w rozmowę.</td></tr></table>";

var tekstOddany = "<br><h3>TYP ODDANY</h3>„WIERNA ŻONA”<br>Osoby Oddane charakteryzują się troską o innych: to ona nadaje sens ich życiu. Nie znajdziecie ludzi bardziej kochających, troskliwych, dbałych o wasze potrzeby i uczucia. Jednostka Oddana jest w swej najlepszej odmianie lojalnym, zawsze pomocnych i rozważnym ''członkiem drużyny'' – czy drużyną tą będzie małżeństwo, rodzina, linia produkcyjna, wydział w biurze, organizacja religijna lub charytatywna, czy jednostka wojskowa. Utożsamia swe potrzeby z potrzebami grupy bądź jej lidera; jej szczęściem jest spełniać pragnienia innych. Osoba Oddana to ktoś, kto mówi ci: „Jestem szczęśliwy, jeżeli ty jesteś szczęśliwa”- i naprawdę tak myśli.<br><br>"
var cechyOddany = "SIEDEM CECH CHARAKTERYSTYCZNYCH:<br> Oto siedem cech kluczowych przy rozpoznawaniu typu Oddanego. Osoba z silna tendencją Oddania będzie częściej i z większa intensywnością przejawiać te zachowania niż ludzie z mniejszą domieszką tego typu.<br> 1.	Zaangażowanie. Ludzie oddani bardzo silnie angażują się w związki. Ich trwałość jest dla nich najwyższą wartością. Szanują instytucję małżeństwa, ale także związki nieoficjalne, nie szczędzą wysiłku, by je utrzymać.<br>2.	Towarzyskość. Wolą towarzystwo jednej lub większej liczby osób od samotności.<br>3.	Zamiłowanie do pracy zespołowej. Częściej podążają za kimś, niż sami przewodzą. Lubią współpracę, szanują autorytety i instytucje. Bez oporów zdają się na innych i przyjmują polecenia.<br>4.	Pokora. Podejmując decyzję, wolą odwołać się do opinii innych i skorzystać  z ich rad.<br>5.	Dążenie do harmonii. Troszczą się, by między sobą a bliskimi budować dobre uczucia. Są uprzejmi, zgodni i pełni taktu.<br>6.	Spolegliwość. Liczą się z innymi ludźmi i lubią sprawiać im przyjemność. W interesie ważnych dla siebie osób są gotowi znosić niewygody.<br>7.	Potrzeba przywiązania. Związki to dla nich są sens życia. Jeżeli stracą najbliższą osobę, wokół której koncentrowały się jej myśli i czyny, potrafią zawrzeć nowe, równie silne więzy z kimś innym.<br><br>"
var tabelaOddany= "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Powój, strażnik ognia, stapiający się, pokorny, towarzyski, szukający harmonii, przywiązany, oddany grupie, spolegliwy, zaangażowany w związki dawca dla wybranych.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Okazuj ciepło, dodaj szczyptę relacji nieformalnej.<br>- Skłaniaj do formułowania własnych oczekiwań.<br>- Niech zaczyna zdanie od „ja” zamiast mówieniu o „trzeba”.<br>- Nie pozwól, by robił za ciebie za dużo.<br>- Zwracaj mu (jej) też uwagę, że nie wszyscy mają taką potrzebę kontaktu jak on (ona).</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Pomóż odróżnić rzeczywiste od wyimaginowanych potrzeb innych.<br>- Ucz je robić krok do tyłu, by inni mogli zrobić krok do przodu.<br>- Łagodź nadmierne przejmowanie się innymi, skupiaj jej uwagę na własnej pracy.<br>- Dbaj o jej zdrowie (wypalanie).<br>- Funduj odosobnienia.<br>- Uważaj, aby nie stała się osobą niezastąpioną.<br>- Zachowaj dystans wobec jej opinii (może schlebiać, ochraniać).<br>- Ucz ją świadomości wpływu tonu głosu i mowy ciała na innych (czasem „Głód w oczach”).</td></tr><tr><th>MOTYWOWANIE</th><td>- Uważaj z krytyką - jeśli już, to odnoś do zachowań, produktów chwaląc OSOBĘ.<br>- Zapewniaj, że jej „nie opuścisz”, zawieraj długofalowe kontrakty, dające bezpieczeństwo.<br>- Uskrzydla ją praca wspólna lub bezpośrednio dla szefa.<br>- Włącz ją w parę, grupkę, zespół.<br>- Korzystaj z jej pomocy i inicjatywy, ale nie uzależniaj się od niej i nie pozwól się uzależnić.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Stwórz atmosferę wspólnej pracy nad problemem. Możesz wykazywać dużą inicjatywę w proponowaniu rozwiązań. Dawaj do zrozumienia twemu partnerowi, jak ważny jest jego udział w procesie negocjacji, oraz jak istotny on jest (twój partner) dla ciebie. Dawaj możliwość wyrażania emocji twemu partnerowi. Trzymaj strukturę - plan, cel, ramy czasowe. Dbaj o dokumentację ustaleń. Nie wywieraj nacisku, presji na partnera przy podejmowaniu przez niego decyzji. Wskazane negocjacje oparte na zasadach (wygrana/wygrana).</td></tr></table>";

var tekstSumienny = "<br><h3>TYP SUMIENNY</h3>„PERFEKCJONISTA”<br>To prawdziwy kręgosłup społeczeństwa. Ludzie z przewagą aspektu Sumiennego mają silne zasady moralne oraz poczucie absolutnej pewności; nie spoczną, dopóki wszystko nie będzie tak, jak należy. Są lojalni wobec swoich rodzin, wobec spraw, w które się angażują i wobec swoich przełożonych. Ciężka praca to znak szczególny tego typu osobowości: ludzie Sumienni stworzeni są do osiągnięć. Żaden wybitny lekarz, prawnik, uczony czy biznesmen nie mógłby zajść tak wysoko, gdyby w jego wzorze osobowości Sumienność nie stanowiła lwiej części. To samo dotyczy komputerowego maniaka, sprawnej gospodyni domowej, księgowego, wzorowego studenta, czy rewelacyjnej sekretarki – w ogóle każdego, kto chce dojść do czegoś ciężką pracą.<br><br>"
var cechySumienny = "OSIEM CECH CHARAKTERYSTYCZNYCH:<br>Oto osiem cech i sposobów zachowania wskazujących na obecność aspektu sumiennego w osobowości. Osoba o silnych tendencjach Sumiennych będzie częściej przejawiać poniższe zachowania i z większą intensywnością niż osoba, w której osobowości typ ten jest słabiej zaznaczony.<br>1.	Ciężka praca. Osoba Sumienna jest oddana pracy, pracuje niezwykle ciężko i jest zdolna do intensywnego, celowego wysiłku.<br>2.	To co należy. Być Perfekcjonistą znaczy być człowiekiem sumienia, silnych zasad i zdecydowanych ocen moralnych, który nie rzuca słów na wiatr w żadnej sprawie. Osoba Sumienna zawsze robi to, co należy.<br>3.	Tak jak trzeba. Wszystko musi być zrobione „tak jak trzeba” i osoba Sumienna zawsze dokładnie wie, co to znaczy – czy chodzi o zachowanie równowagi finansowej, realizację planów kierownictwa, czy tez o ułożenie brudnych naczyń w zmywarce.<br>4.	Perfekcjonizm. Osoba Sumienna lubi, kiedy każde zadanie i projekt są zapięte na ostatni guzik, wolne od najmniejszych nawet niedociągnięć.<br>5.	Upór. Perfekcjoniści trzymają się swoich przekonań i poglądów. Sprzeciw najczęściej tylko wzmaga ich upór i determinację.<br>6.	Porządek i umiłowanie szczegółu. Ludzie sumienni lubią, kiedy wokół nich panuje porządek i schludność. Są dobrymi organizatorami, wyżywają się w sporządzaniu list i katalogów. Nie ma dla nich sprawy zbyt drobnej, by się nią zajmować.<br>7.	Ostrożność. Perfekcjoniści są oszczędni, uważni i ostrożni we wszystkich dziedzinach życia; niezdolni do beztroskiej utraty samokontroli, nie oddają się dzikim ekscesom.<br>8.	Przywiązanie do rzeczy. Osoba Sumienna często jest „chomikiem”; gromadzi różne przedmioty, jest niezdolna do wyrzucenia rzeczy, która była kiedyś przydatna lub mogłaby przydać się w przyszłości.<br><br>"
var tabelaSumienny = "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Perfekcyjny, świetnie zorganizowany, normocentryczny (najważniejsze zasady), dąży do doskonałości, pracowity, uparty, ostrożny, porządny, solidny, w stresie obsesyjny lub grzęźnie w detalach.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Rzeczowo, jasno, bez ogólników.<br>- Często na piśmie.<br>- Bez emocji i upiększania.<br>- Licz się z ich krytycyzmem – umieszczaj go w konstruktywnym kontekście.<br>- Przygotowuj się do spotkań.<br>- Dyskutuj każdy argument.<br>- Nie unoś się.<br>- Proś o wyrażanie zarzutów, żalów, pretensji.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Lubi działania intensywne, długoterminowe, wymagające dokładności i koncentracji na detalach.<br>- Gdyby ugrzązł w detalach przyjmij „wystarczająco dobry” rezultat i popychaj dalej.<br>- Wskazuj na cel, gdy skupi się zbyt na procedurach.<br>- Bierz pod uwagę, że może być czasem rozgniewany choć to ukrywa lub potrzebuje „słusznej sprawy”, by to ujawnić.</td></tr><tr><th>MOTYWOWANIE</th><td>- Wyraź swoje uznanie mimo, że o to nie prosi i mało reaguje na pochwały.<br>- Ustal wskaźniki i wyliczaj dokładnie wysokość premii.<br>- Proponuj twórcze plany z wysokim standardem realizacji.<br>- Bądź bardzo uczciwy i dbaj o konsekwencje.<br>- Chroń od osób pasywnych, bałaganiarzy, krętaczy.<br>- Oswajaj z błędami (nikt nie jest doskonały...).</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Ważne są szczegóły i detale – umowa, kontrakt itp. Jasne i klarowne zasady prowadzenia rozmów. Nie lubi kiedy partner wyraża otwarty sprzeciw wobec jego propozycji, stanowiska – może wzmocnić jego opór, trwanie przy swoim. Jest lojalny wobec swoich przełożonych (nie próbuj wchodzić z nim w koalicje przeciw jego zwierzchnikom). Przyjmuj krytykę, przyznaj się do błędu, ale utrzymuj obrany przez ciebie cel. Do rozmów siadaj przygotowany merytorycznie z planem, celem – wzbudzisz szacunek sumiennego partnera. Nie oczekuj, że twój partner zmieni szybko stanowisko – wręcz przeciwnie daj mu czas na pomyślenie. Będziesz miał kłopoty, jeśli liczysz na specjalne traktowanie, lub dasz upust swojej agresji. Kompromis to jedno z bardziej praktycznych rozwiązań w trudnych negocjacjach. Wskazane negocjacje oparte na zasadach wygrana-wygrana z elementami twardymi lub negocjacje twarde.</td></tr></table>";

var tekstWygodny = "<br><h3>TYP WYGODNY</h3>„KALIFORNIJCZYK”<br>Wolność bycia sobą – nikt nie odbierze tego prawa osobie o Wygodnym typie osobowości. Tacy ludzie podporządkowują się regułom gry, wypełniają swe obowiązki i dotrzymują zobowiązań. Ale kiedy mają czas wolny, nie pozwolą, by jakakolwiek osoba, instytucja czy nawet norma kulturowa przeszkodziła im w pogoni za osobistym szczęściem. W tym bowiem dla osoby wygodnej zawiera się istota życia. Niektórzy odnajdują owo szczęście w poszukiwaniach twórczych, inni w lekturze dobrej książki. Nie tak ważny jest wybrany rodzaj rozrywki, jak samo prawo do niej. Gdy jest ono zagrożone, ci bezkonfliktowi zwykle ludzie energicznie stają w obronie fundamentalnej dla nich wolności „robienia swojego”.<br><br>"
var cechyWygodny = "SIEDEM CECH CHARAKTERYSTYCZNYCH<br>Oto siedem kluczowych cech i postaw charakterystycznych dla typu Wygodnego. Osoba o silnych tendencjach Wygodnych będzie wykazywać większą liczbę tych zachowań i z większą intensywnością niż ktoś, w kogo osobowości typ ten jest mniej dominujący.<br>1.	Niezbywalne prawo. Ludzie o osobowości Wygodnej wierzą w  swoje prawo do spędzania własnego czasu na własny sposób. Cenią wygodę, czas wolny i własną drogę do szczęścia i gotowi są ich bronić.<br>2.	Co za dużo, to niezdrowo. Gotowi są podporządkować się regułom gry. Robią dokładnie tyle, ile się od nich wymaga, i nic ponadto. Oczekują od innych poszanowania tej zasady.<br>3.	Prawo do oporu. Nie pozwalają się wykorzystywać. Bez skrępowania przeciwstawią się żądaniom idącym ich zdaniem za daleko lub przekraczającym ich zakres obowiązków.<br>4.	Może jutro... Mają swobodny stosunek do czasu. Nie dają się opętać pilnym sprawom i wskazówkom zegara. Dla nich pośpiech to kłopot i zbędne zamieszanie. Pogodnie i optymistycznie zakładają, że to, co trzeba zrobić, jakoś w końcu się zrobi.<br>Jestem w porządku. Nie są zapatrzeni w autorytety. Akceptują siebie i swój sposób życia.<br>6.	Wiara w koło fortuny. Uważają, że nie są gorsi od innych i zasługują na wszystkie dobre rzeczy, które niesie życie. Utrzymują, że to ślepy los często decyduje o tym, komu się powiedzie, a komu nie.<br>7.	Mieszane uczucia. Temperament popycha ich do robienia wszystkiego po swojemu, ale jeśli mogliby przez to popaść w konflikt z ważnymi dla siebie osobami, przeżywają rozterkę. Choć pragną wolności, nie lubią narażać na ryzyko swych związków.<br><br>"
var tabelaWygodny ="<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>- Po swojemu, w swoim tempie, unika konfliktów, robi sobie dobrze, niezależny od autorytetów,  nie lubi być wykorzystywany, w stresie stosuje bierny opór.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Jeśli nie mówi „tak”, „być może” mówi „nie”, nie zakładaj, że milczenie oznacza zgodę.<br>- Robiąc uzgodnienia dopytuj o jego potrzeby i interesy, aby nie zgodził się tylko „dla świętego spokoju”.<br>- Uzasadniaj polecenia interesem firmy, składaj je w formie propozycji, na których sposób realizacji będzie miał wpływ.<br>- Jeśli z uwagi na skłonność do dygresji i długich wypowiedzi pomija istotę sprawy ; przerwij i proś o pomoc w dotarciu do sedna problemu.<br>- Jasno informuj o swoich potrzebach – nie licz, że je odgadnie.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Planuj, powracaj do rozmowy o projekcie, dostarczaj struktury, przypominaj o celach.<br>- Sprawdzaj, czy wychwytuje priorytety.<br>- Dyskretnie monitoruj jego działania, nie pozwól, aby informacje zwrotne a zwłaszcza wzajemne pretensje kumulowały się.<br>- Ucz go przez modelowanie konstruktywnego wyrażania krytyki i pretensji.<br>- Problemami zajmuj się tylko, gdy się pojawiają, rób to życzliwie.<br>- Jeśli zwleka, odrzuca, zapomina – zapytaj, o co ma żal.</td></tr><tr><th>MOTYWOWANIE</th><td>- Nigdy nie mów „musisz”.<br>- Pamiętaj, że uskrzydla go autonomia, praca tak jak chce, wtedy kiedy chce (uwzględniaj to tak dalece jak to możliwe).<br>- Nie próbuj go zmieniać.<br>- Interesuj się jego światem.<br>- Nie krytykuj za to, że tylko „robi swoje”.<br>- Nagradzaj zwiększeniem swobody.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Nie narzucaj arbitralnie zasad i ram – pozwól na jego udział w podejmowaniu decyzji co do warunków prowadzenia rozmów. Testuj zrozumienie – sprawdzaj zwłaszcza brak komunikatu TAK – prawdopodobnie oznacza to NIE. Pytaj o jego potrzeby. Dbaj o dokumentację rozmowy (ustaleń). Elastycznie utrzymuj strukturę rozmowy – plan, cel, ramy czasowe. Bądź konkretny i rzeczowy – prowokuj (modeluj) rzeczowość z jego strony. Sprowadzaj rozmowę do istoty problemu. Namawiaj go do jawnego wyrażania krytyki – sam wypowiadaj jasno i rzeczowo krytyczne uwagi.</td></tr></table>";

var tekstWladczy = "<br><h3>TYP WŁADCZY</h3>„PRZYWÓDCA STADA”<br>Kto tu rządzi? Wiadomo –typ Władczy. Inni zaledwie aspirują do przywództwa, ludzie władczy sięgają po nie instynktownie. Są urodzonymi liderami, jak najsilniejszy pies w stadzie. Ich typ osobowości jest silny, obdarzony naturalną mocą w większym stopniu niż wszystkie inne. Potrafią brać na siebie ogromną odpowiedzialność bez obawy przed klęską. Swobodnie sprawują władzę. Nigdy nie ustępują pola. Walczą z poczuciem wyższości mistrza.<br>To, w jaki sposób ci ludzie użyją swojej siły, której zawsze mają w nadmiarze, zależy od innych aspektów ich wzoru  osobowości. W służbie wielkiej sprawy osoba Władcza może stać się wspaniałym przywódcą, zwłaszcza w sytuacji kryzysowej.<br><br>"
var cechyWladczy = "SZEŚĆ CECH CHARAKTERYSTYCZNYCH<br>Oto sześć cech kluczowych dla rozpoznania typu Władczego. Osoba o silnych tendencjach Władczych będzie wykazywała więcej z tych zachowań i zwiększą intensywnością niż osoba, w której osobowości ten aspekt jest mniej dominujący.<br>1.	Przywództwo. Ludzie władczy biorą władzę w swoje ręce. Dobrze czują się w roli przywódcy obdarzonego autorytetem i odpowiedzialnością. <br>2.	Szacunek dla hierarchii.  Najlepiej funkcjonują w ramach tradycyjnych struktur, gdzie każdy zna swoje miejsce, a zasady podporządkowania są jasno wyznaczone.<br>3.	Żelazna dyscyplina. Są niezwykle zdyscyplinowani i wszystkim, którzy im podlegają, również narzucają wyraźne reguły.<br>4.	Celowość w działaniu. Konsekwentnie dążą do swoich celów. Żeby je osiągnąć, przybierają postawę praktyczną i pragmatyczną. Zrobią wszystko, co niezbędne.<br>5.	Odwaga. Nie sposób ich oskarżyć o tchórzliwość czy małoduszność. Śmiało i skutecznie działają w trudnych i niebezpiecznych sytuacjach, strach nie jest dla nich hamulcem.<br>6.	Twardziele. Lubią akcję i przygodę. Są odporni fizycznie, często zajmują się sportem wyczynowym, zwłaszcza walkami sportowymi.<br><br>"
var tabelaWladczy= "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>Agresywny, kontrolujący, apodyktyczny, zdyscyplinowany, twardy, zorientowany na cel, odważny, twardy, w stresie bezwzględny.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Jasne określenie pozycji w hierarchii.<br>- Jasne określenie własnego stanowiska.<br>- Słuchanie, uznanie gniewu.<br>- Informacje zwrotne, na bieżąco – bardzo dobrze przygotowanie.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Realistyczne plany.<br>- Włączanie ludzi, delegowanie odpowiedzialności.<br>- Uwrażliwienie na jakość relacji z ludźmi (możliwy na kryzys).<br>- Nieformalne spotkania.</td></tr><tr><th>MOTYWOWANIE</th><td>- Szacunek, uczciwość, sojusz.<br>- Twarde dyskusje, pełna otwartość, oczekiwanie wzajemności.<br>- Jasne określenie sfery wpływów i kontroli.<br>- Zarządzanie przez cele.<br>- Wysokie standardy.<br>- Twórcze kanalizowanie siły.<br>- Ew. odwołanie się do uznanej wyższej władzy.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Siadając do rozmów miej jasno sprecyzowany cel. Dbaj o przestrzeganie ram czasowych, które wcześniej ustaliłeś. Broniąc odważnie swojego stanowiska zasłużysz na szacunek, ale nie oczekuj, że to się spodoba twojemu partnerowi. Nie idź na kompromis – twój partner od razu potraktuje to, jako odznakę twojej słabości. Jeśli wygrywasz – przedefiniuj sytuację, żeby wyszedł remis Dawaj do zrozumienia, że rozumiesz jego stanowisko  i jego interesy, przedstawiaj swoje. Unikaj eskalacji konfliktu i wracaj do spraw zasadniczych. Nie oczekuj na pochwały i aprobatę twoich pomysłów – sam również nie stosuj tego rodzaju zabiegów. Daj prawo swemu rozmówcy do wyrażania negatywnych emocji (gniewu, agresji) – wytrzymuj to. Jeśli popełnisz błąd – przyznaj się, ale nie kajaj się. Wskazane negocjacje twarde i oparte na zasadach.</td></tr></table>";

var tekstOfiarny = "<br><h3>TYP  OFIARNY</h3>„ALTRUISTA”<br>Życie jest służbą, miłość jest ofiarą. Oto dwa aksjomaty ludzi, których osobowość jest typu Ofiarnego. Uważają, że ich potrzeby mogą zaczekać, aż wszyscy inni zostaną zaspokojeni. Składając siebie w ofierze zyskują spokój, bezpieczeństwo i pewność swego miejsca w porządku świata. W najlepszym i najszlachetniejszym wydaniu jest typ pełen bezinteresowności i wielkoduszności, materiał na świętych przykładnych obywateli.<br><br>"
var cechyOfiarny = "SIEDEM CECH CHARAKTERYSTYCZNYCH:<br>Oto siedem cech kluczowych dla rozpoznania typu ofiarnego. Osoba z silnym aspektem Ofiarnym będzie wykazywała więcej z wymienionych niżej zachowań i z większą intensywnością niż osoba, w której osobowości aspekt ten jest mniej dominujący.<br>1.	Wspaniałomyślność. Jeżeli jesteś w potrzebie, osoba ofiarna odda ci ostatnią koszulę. Nie będzie czekać, aż poprosisz.<br>2.	W służbie bliźniego. Dyrektywą naczelną Altruistów jest: być użytecznym. Z szacunku dla innych rezygnują z własnych ambicji i współzawodnictwa. Zadowala ich druga pozycja, a nawet ostatnia.<br>3.	Uważność. Ludzie Ofiarni odnoszą się do innych z wielkimi względami. Są  uczciwi i godni zaufania.<br>4.	Tolerancja. Są nieskorzy do osądzania i pobłażliwi wobec cudzych słabości. Nigdy nie czynią nikomu wyrzutów. Pozostaną ci wierni na dobre i na złe.<br>5.	Pokora. Obce im są zrozumiałość i duma, nie lubią robić wokół siebie hałasu. Nie pragną być ośrodkiem uwagi i źle się czują w świetle reflektorów.<br>6.	Wytrzymałość. Potrafią wytrwale znosić cierpienie. Wolą sami dźwigać swój krzyż. Mają wiele cierpliwości i odporności na niewygody.<br>7.	Prostoduszność. Są naiwni i niewinni. Nie zdają sobie sprawy z wielkiego wpływu, jaki często wywierają na innych. Nie podejrzewają nigdy skrytych lub pokrętnych intencji u ludzi, którym tak wiele dają.<br><br>"
var tabelaOfiarny= "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>- Społecznik, preferuje ciężar, pomocny, wspaniałomyślny, prostoduszny, uczciwy, wytrzymały, tolerancyjny, poświęcający się, dawca, w stresie – w roli „ofiary”.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Dostrzegaj i doceniaj pomocną postawę przyjmując oddanie i poświęcenia nie wywyższaj się zaproponuj czasem coś wspólnego.<br>- Pomagaj wyrażać złość, pretensje.<br>- Jego „muszę” zamieniaj na „decydujesz”.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Przyjmij to, co ci oferuje, ale selektywnie, uważaj, by go nie wykorzystywać; jeśli odmawiasz przyjęcia przysługi wskazuj dlaczego.<br>- Dziel zadania na etapy.<br>- Sprawdzaj, czy nie potrzebuje czegoś dla siebie lub awansu - sam(a) nie poprosi.<br>- Pilnuj, aby nie wchodził(a) w rolę ofiary. Uważaj na prowokację do gniewu lub odrzucenia.</td></tr><tr><th>MOTYWOWANIE</th><td>- Dobrze znoszą nudne, rutynowe zadania.<br>- „Zrób to dla mnie, w tobie nadzieja” ale potem zawrzyj jasny kontrakt.<br>- Obciążaj (bez pustych przerobów), ale:<br>- Nie dopuszczaj do przeciążenia<br>- Publiczne podziękowanie „na żywo” krępują go (ją), ale dyskretnie okazuj wdzięczność i doceniaj.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Staraj się nadać  sprawie (procesowi negocjacji) aspekt dużej wagi – misji. Wykazuj wspólny interes – sukces w osiągnięciu porozumienia. Wykazuj możliwość stworzenia koalicji w pracy nad problemem . Doceniaj gesty ofiarności ze strony partnera, ale uważaj, abyś nie popadł w zasadzkę (zależność). Sam również nie wykorzystuj jego ofiarności. Nie wywyższaj się. Wskazane przede wszystkim negocjacje oparte na zasadach – wygrana / wygrana , nastawione na szukanie wspólnych rozwiązań.</td></tr></table>";

var tekstPowazny = "<br><h3>TYP POWAŻNY</h3>„REALISTA”<br>Ludzie Poważni nie żywią żadnych złudzeń. Nie sięgają po gwiazdkę z  nieba, nie mówią hop, zanim nie przeskoczą, nie noszą różowych okularów i nie traktują życia jak wiecznego świata. Nawet kiedy sprawy nie przedstawiają się wesoło, oni widzą  je dokładnie takimi, jakie są. Współczesna kultura faworyzuje jednostki, które „myślą pozytywnie”, wszędzie dostrzegają jasne strony i nieustannie pracują nad sobą. Osoba o typie Poważnym niezbyt pasuje do tego obrazu. Ale ludziom Poważnym nie zależy na popularności.Co Realista traci, nie bujając w obłokach, to zyskuje dzięki swej umiejętności znoszenia wszystkiego, co najgorsze. Żaden inny typ osobowości nie okazuje się tak wytrzymały, kiedy ciemne chmury gromadzą się nad ziemią. Jest trzeźwy, przyziemny i praktyczny, jego siła pomoże każdemu przetrwać ciężkie chwile. Jak kilka innych typów, potrafi zajść daleko małymi krokami.<br><br>"
var cechyPowazny = "SIEDEM CECH CHARAKTERYSTYCZNYCH:<br>1.	Powaga. Ludzie  z Poważnym typem osobowości zawsze zachowują trzeźwość umysłu. Są solenni i nieskorzy do ekspresji uczuciowej.<br>2.	Bezpretensjonalność. Realistycznie oceniają swoje możliwości i są świadomi swoich ograniczeń. Obca jest im próżność i pycha.<br>3.	Poczucie odpowiedzialności. Są gotowi odpowiadać za swoje postępowanie. Nie tuszują swoich błędów, by uciec od ich konsekwencji.<br>4.	Rozwaga. Zwykli wszystko rozważać, analizować i oceniać. Zanim coś uczynią, zawsze zważą wszystkie za i przeciw.<br>5.	Brak złudzeń. Krytycznie patrzą na bliźnich. Oceniają innych również bezwzględnie jak samych siebie.<br>6.	Żadnych niespodzianek. Przewidują możliwe trudności, kiedy więc dochodzi do najgorszego, są przygotowani.<br>7.	Wrażliwość sumienia. Ogromnie cierpią kiedy uświadomią sobie, że zachowali się bezmyślnie lub nietaktownie.<br><br>"
var tabelaPowazny= "<table class='tabelaCechy'><tr><th>ISTOTA TYPU</th><td>„Szklanka od połowy pusta”; rozważny, odpowiedzialny, realizm do bólu, zero złudzeń, gotowy na najgorsze, wrażliwe sumienie, trud i znój, w stresie może reagować depresją.</td></tr><tr><th>KOMUNIKOWANIE SIĘ</th><td>- Adresuj komunikaty do jego trzeźwego umysłu. Nie upiększaj, nie fantazjuj.<br>- Uwzględniaj jego punkt widzenia, ale ni daj się zdołować.<br>- Nie uszczęśliwiaj go na siłę, nie namawiaj na entuzjazm i optymizm.<br>- Ponuractwa i braku entuzjazmu nie bierz przeciwko sobie.</td></tr><tr><th>KIEROWANIE I ZARZĄDZANIE</th><td>- Sumienny w wykonywaniu obowiązków, zaharowuje się niezależnie od wynagrodzenia -> nie ulegaj pokusie nadużywania go.<br>- Chroń go - nie broni swoich praw.<br>- Podejmuje się trudnych prac, odporny na niewygodę.</td></tr><tr><th>MOTYWOWANIE</th><td>- Lubi bolesną satysfakcję w stylu „a nie mówiłem”.<br>- Zlecaj opanowanie procedur awaryjnych, alternatyw.<br>- Wykazuj inicjatywę, nie czekaj, aż sam coś sobie „zada”.<br>- Nie bij brawa, ale doceniaj i okazuj wdzięczność.</td></tr><tr><th>NEGOCJACJE I ROZMOWY HANDLOWE</th><td>Bądź rzeczowy i konkretny. Miej jasny plan i cel rozmów. Wykazuj, podkreślaj obszary odpowiedzialności twojej i twojego partnera. Wywiązuj się z podjętych zobowiązań. Traktuj krytykę wyrażoną przez twego partnera jako jego „język porozumiewania się” – jako zachowanie testujące pomysły, stanowiska. Nie traktuj tego jako krytyki twojej osoby. Unikaj wyrażania głębszych uczuć (obfitej ekspresji). Podejmuj wspólne analizy i rozważania pomysłów i rozwiązywania, stanowisk. Nie zaskakuj go niespodziewanymi decyzjami.</td></tr></table>";



var teksty = [tekstCzujny, tekstSamotniczy, tekstNiezwyczajny, tekstAwanturniczy, tekstZmienny, tekstDramatyczny, tekstPewnySiebie, tekstOstrozny, tekstOddany, tekstSumienny, tekstWygodny, tekstWladczy, tekstOfiarny, tekstPowazny];
var cechy = [cechyCzujny, cechySamotniczy,cechyNiezwyczajny,cechyAwanturniczy,cechyZmienny, cechyDramatyczny, cechyPewnySiebie, cechyOstrozny, cechyOddany, cechySumienny, cechyWygodny, cechyWladczy, cechyOfiarny, cechyPowazny];
var tabele = [tabelaCzujny, tabelaSamotniczy,tabelaNiezwyczajny,tabelaAwanturniczy,tabelaZmienny, tabelaDramatyczny, tabelaPewnySiebie, tabelaOstrozny, tabelaOddany, tabelaSumienny, tabelaWygodny, tabelaWladczy, tabelaOfiarny, tabelaPowazny];



